### PR TITLE
Iteration5

### PR DESCRIPTION
**Pull request by RyukungG**
Finish refactor and add more question

### CODE REVIEW

**Comment by Halcyon905** [comment]
Logging text when player coins from treasure is wrong.

**Review by SeventwoZ — COMMENTED** [review]
Forget doctstrings in test_get_player and test_found_monster_after_exit.

**Review by Halcyon905 — APPROVED** [review]
wake up samurai, its time to merge.

**Review by SeventwoZ — APPROVED** [review]
Sir yes sir!

**Review by MarojT — APPROVED** [review]
Nice.

**Pull request merged**
